export type EmojiCategoryId = 'mood' | 'activity' | 'nature' | 'objects' | 'emotions';

export interface EmojiDefinition {
  symbol: string;
  name: string;
  description: string;
  keywords: string[];
  category: EmojiCategoryId;
  tone?: 'warm' | 'cool' | 'neutral' | 'playful';
  clusters?: string[];
  contexts?: Array<'title' | 'content'>;
}

export interface EmojiCategory {
  id: EmojiCategoryId;
  label: string;
  description: string;
  accent: string;
}

export interface EmojiFilter {
  id: string;
  label: string;
  icon: string;
  keywords: string[];
  tone?: EmojiDefinition['tone'];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'mood',
    label: 'Mood & Vibes',
    description: 'Expressive faces and reactions that set the tone of your message.',
    accent: 'from-amber-400/40 via-orange-400/30 to-pink-400/40',
  },
  {
    id: 'activity',
    label: 'Activities',
    description: 'Moments in motion – celebrations, adventures, and everyday actions.',
    accent: 'from-blue-400/30 via-sky-400/20 to-cyan-400/40',
  },
  {
    id: 'nature',
    label: 'Nature & Weather',
    description: 'Skies, seasons, and natural elements to ground your story.',
    accent: 'from-emerald-400/30 via-lime-400/20 to-teal-400/40',
  },
  {
    id: 'objects',
    label: 'Objects & Symbols',
    description: 'Tools, artifacts, and icons to anchor concrete ideas.',
    accent: 'from-purple-400/30 via-indigo-400/20 to-fuchsia-400/40',
  },
  {
    id: 'emotions',
    label: 'Hearts & Feelings',
    description: 'Affectionate gestures and heartfelt sentiments.',
    accent: 'from-rose-400/40 via-red-400/30 to-pink-400/40',
  },
];

export const EMOJI_FILTERS: EmojiFilter[] = [
  {
    id: 'uplifting',
    label: 'Uplifting',
    icon: '✨',
    keywords: ['bright', 'celebrate', 'joy', 'glow', 'shine'],
    tone: 'warm',
  },
  {
    id: 'calming',
    label: 'Calming',
    icon: '🌊',
    keywords: ['calm', 'breeze', 'night', 'relax', 'peace'],
    tone: 'cool',
  },
  {
    id: 'focus',
    label: 'Focus',
    icon: '🎯',
    keywords: ['idea', 'target', 'spark', 'focus', 'work'],
    tone: 'neutral',
  },
  {
    id: 'playful',
    label: 'Playful',
    icon: '🎉',
    keywords: ['party', 'fun', 'dance', 'play', 'yay'],
    tone: 'playful',
  },
];

export const EMOJI_DEFINITIONS: EmojiDefinition[] = [
  {
    symbol: '😀',
    name: 'Grinning Face',
    description: 'Bright and friendly – great for cheerful intros.',
    keywords: ['smile', 'happy', 'joy', 'welcome', 'hello'],
    category: 'mood',
    tone: 'warm',
    clusters: ['smiles', 'introductions'],
  },
  {
    symbol: '😄',
    name: 'Beaming Smile',
    description: 'A big, enthusiastic grin that radiates positivity.',
    keywords: ['smile', 'delight', 'cheerful', 'energy', 'yay'],
    category: 'mood',
    tone: 'warm',
    clusters: ['smiles'],
  },
  {
    symbol: '😊',
    name: 'Soft Smile',
    description: 'Gentle and grateful – a subtle expression of warmth.',
    keywords: ['smile', 'warm', 'kind', 'grateful', 'soft'],
    category: 'mood',
    tone: 'warm',
    clusters: ['smiles', 'gratitude'],
  },
  {
    symbol: '😉',
    name: 'Playful Wink',
    description: 'A playful nudge or hint of humor.',
    keywords: ['wink', 'playful', 'hint', 'tease', 'fun'],
    category: 'mood',
    tone: 'playful',
    clusters: ['humor'],
  },
  {
    symbol: '🥳',
    name: 'Party Popper',
    description: 'Celebrate wins, launches, or big reveals.',
    keywords: ['party', 'celebrate', 'yay', 'launch', 'milestone'],
    category: 'activity',
    tone: 'playful',
    clusters: ['celebrations'],
  },
  {
    symbol: '🤝',
    name: 'Handshake',
    description: 'Ideal for partnerships, agreements, or collaborative work.',
    keywords: ['team', 'partnership', 'agreement', 'ally', 'welcome'],
    category: 'activity',
    tone: 'neutral',
    clusters: ['collaboration'],
    contexts: ['title'],
  },
  {
    symbol: '💡',
    name: 'Idea Spark',
    description: 'A bright idea or creative insight, perfect for titles.',
    keywords: ['idea', 'spark', 'lightbulb', 'insight', 'focus'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['ideas', 'innovation'],
    contexts: ['title'],
  },
  {
    symbol: '🧠',
    name: 'Brainstorm',
    description: 'Highlights clever thinking or strategy.',
    keywords: ['brain', 'strategy', 'plan', 'smart', 'focus'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['ideas'],
  },
  {
    symbol: '🔥',
    name: 'On Fire',
    description: 'Use for high energy moments, wins, or hot topics.',
    keywords: ['fire', 'hot', 'energy', 'trending', 'motivation'],
    category: 'nature',
    tone: 'warm',
    clusters: ['momentum'],
  },
  {
    symbol: '🌅',
    name: 'Sunrise',
    description: 'Fresh starts, optimism, and new beginnings.',
    keywords: ['sunrise', 'dawn', 'new', 'hope', 'sun'],
    category: 'nature',
    tone: 'warm',
    clusters: ['beginnings'],
  },
  {
    symbol: '🌞',
    name: 'Radiant Sun',
    description: 'Bright, sunny energy with an uplifting feel.',
    keywords: ['sun', 'bright', 'warm', 'joy', 'shine'],
    category: 'nature',
    tone: 'warm',
    clusters: ['weather'],
  },
  {
    symbol: '🌈',
    name: 'Rainbow',
    description: 'Colorful positivity and hopeful outcomes.',
    keywords: ['rainbow', 'hope', 'colorful', 'joy', 'inclusive'],
    category: 'nature',
    tone: 'playful',
    clusters: ['weather'],
  },
  {
    symbol: '🌿',
    name: 'Fresh Leaf',
    description: 'Grounding, calm, and sustainable vibes.',
    keywords: ['leaf', 'nature', 'calm', 'fresh', 'growth'],
    category: 'nature',
    tone: 'cool',
    clusters: ['calm'],
  },
  {
    symbol: '💫',
    name: 'Sparkle Trail',
    description: 'A hint of magic or transformation.',
    keywords: ['sparkle', 'magic', 'glow', 'shine', 'moment'],
    category: 'objects',
    tone: 'playful',
    clusters: ['magic'],
  },
  {
    symbol: '✨',
    name: 'Stardust',
    description: 'Add shimmer to exciting updates or wins.',
    keywords: ['sparkle', 'shine', 'glitter', 'bright', 'moment'],
    category: 'objects',
    tone: 'playful',
    clusters: ['magic'],
  },
  {
    symbol: '📣',
    name: 'Announcement',
    description: 'Call attention to announcements or releases.',
    keywords: ['announce', 'megaphone', 'news', 'launch', 'share'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['communication'],
    contexts: ['title'],
  },
  {
    symbol: '📝',
    name: 'Memo',
    description: 'Great for notes, writing prompts, or calls to action.',
    keywords: ['write', 'note', 'memo', 'plan', 'document'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['writing'],
    contexts: ['content'],
  },
  {
    symbol: '🔍',
    name: 'Discovery',
    description: 'Spotlight analysis, research, or curiosity.',
    keywords: ['search', 'discover', 'analyze', 'inspect', 'focus'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['research'],
  },
  {
    symbol: '📈',
    name: 'Growth Chart',
    description: 'Progress, results, and upward trends.',
    keywords: ['growth', 'chart', 'stats', 'progress', 'up'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['momentum'],
  },
  {
    symbol: '🎯',
    name: 'Bullseye',
    description: 'Sharp focus, hitting targets, and goals achieved.',
    keywords: ['focus', 'goal', 'target', 'precision', 'win'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['focus'],
  },
  {
    symbol: '🚀',
    name: 'Rocket Launch',
    description: 'Momentum, launches, and ambitious moves.',
    keywords: ['rocket', 'launch', 'start', 'project', 'future'],
    category: 'activity',
    tone: 'playful',
    clusters: ['beginnings'],
    contexts: ['title'],
  },
  {
    symbol: '🛠️',
    name: 'Build Mode',
    description: 'Hands-on progress, tinkering, and making.',
    keywords: ['tools', 'build', 'craft', 'fix', 'maker'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['craft'],
  },
  {
    symbol: '🧭',
    name: 'Guiding Compass',
    description: 'Direction-setting, strategy, or navigation cues.',
    keywords: ['compass', 'direction', 'explore', 'guide', 'plan'],
    category: 'objects',
    tone: 'cool',
    clusters: ['explore'],
  },
  {
    symbol: '💬',
    name: 'Dialogue Bubble',
    description: 'Highlights conversation, feedback, or discussion.',
    keywords: ['chat', 'dialogue', 'feedback', 'conversation', 'talk'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['communication'],
  },
  {
    symbol: '❤️',
    name: 'Classic Heart',
    description: 'Bold affection, appreciation, or celebration.',
    keywords: ['love', 'heart', 'care', 'gratitude', 'support'],
    category: 'emotions',
    tone: 'warm',
    clusters: ['gratitude'],
  },
  {
    symbol: '💖',
    name: 'Sparkling Heart',
    description: 'Adds sparkle to thank-yous or celebratory notes.',
    keywords: ['heart', 'sparkle', 'gratitude', 'celebrate', 'shine'],
    category: 'emotions',
    tone: 'playful',
    clusters: ['gratitude'],
  },
  {
    symbol: '🤗',
    name: 'Open Arms',
    description: 'Warm, welcoming support or congratulations.',
    keywords: ['hug', 'welcome', 'support', 'happy', 'care'],
    category: 'emotions',
    tone: 'warm',
    clusters: ['support'],
  },
  {
    symbol: '🙌',
    name: 'Celebration Raise',
    description: 'Hands up for achievements and applause.',
    keywords: ['celebrate', 'yay', 'high five', 'success', 'cheer'],
    category: 'activity',
    tone: 'playful',
    clusters: ['celebrations'],
  },
  {
    symbol: '🌙',
    name: 'Calm Moon',
    description: 'Evening updates, wind-down notes, or reflective tone.',
    keywords: ['moon', 'night', 'calm', 'reflect', 'rest'],
    category: 'nature',
    tone: 'cool',
    clusters: ['calm'],
  },
  {
    symbol: '💤',
    name: 'Rest Mode',
    description: 'Signals rest, downtime, or finishing for the day.',
    keywords: ['rest', 'sleep', 'pause', 'calm', 'night'],
    category: 'mood',
    tone: 'cool',
    clusters: ['calm'],
  },
  {
    symbol: '⚡',
    name: 'Electric Energy',
    description: 'Quick wins, bold ideas, or lightning-fast updates.',
    keywords: ['energy', 'fast', 'electric', 'power', 'spark'],
    category: 'nature',
    tone: 'warm',
    clusters: ['momentum'],
  },
  {
    symbol: '📚',
    name: 'Knowledge Stack',
    description: 'Learning moments, documentation, or references.',
    keywords: ['learn', 'books', 'knowledge', 'study', 'library'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['learning'],
  },
  {
    symbol: '🧩',
    name: 'Puzzle Piece',
    description: 'Problem solving, fit, or strategic alignment.',
    keywords: ['puzzle', 'fit', 'strategy', 'solution', 'piece'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['strategy'],
  },
  {
    symbol: '🪴',
    name: 'Nurtured Plant',
    description: 'Growth in progress, nurturing ideas, or patient development.',
    keywords: ['growth', 'plant', 'nurture', 'care', 'progress'],
    category: 'nature',
    tone: 'cool',
    clusters: ['growth'],
  },
  {
    symbol: '🛫',
    name: 'Takeoff',
    description: 'Starting a journey, travel, or new adventure.',
    keywords: ['travel', 'takeoff', 'begin', 'journey', 'flight'],
    category: 'activity',
    tone: 'neutral',
    clusters: ['beginnings'],
  },
  {
    symbol: '🎨',
    name: 'Creative Palette',
    description: 'Artistic flair, visual storytelling, or design updates.',
    keywords: ['creative', 'art', 'design', 'palette', 'color'],
    category: 'activity',
    tone: 'playful',
    clusters: ['creativity'],
  },
  {
    symbol: '🧪',
    name: 'Experiment Mode',
    description: 'Testing, research, or experimental work.',
    keywords: ['experiment', 'lab', 'test', 'science', 'iteration'],
    category: 'activity',
    tone: 'neutral',
    clusters: ['research'],
  },
  {
    symbol: '🧵',
    name: 'Threaded Story',
    description: 'Weaving narratives or connecting themes.',
    keywords: ['thread', 'story', 'weave', 'connect', 'narrative'],
    category: 'objects',
    tone: 'cool',
    clusters: ['storytelling'],
  },
  {
    symbol: '🌟',
    name: 'Spotlight Star',
    description: 'Highlight standout ideas or VIP moments.',
    keywords: ['star', 'highlight', 'spotlight', 'shine', 'notable'],
    category: 'objects',
    tone: 'warm',
    clusters: ['magic'],
  },
  {
    symbol: '🎵',
    name: 'Musical Note',
    description: 'Tone setting, rhythm, or audio cues.',
    keywords: ['music', 'note', 'tone', 'vibe', 'song'],
    category: 'activity',
    tone: 'playful',
    clusters: ['creativity'],
  },
  {
    symbol: '📌',
    name: 'Pinpoint',
    description: 'Mark important reminders or next steps.',
    keywords: ['pin', 'reminder', 'note', 'save', 'important'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['organization'],
  },
  {
    symbol: '🛡️',
    name: 'Shielded',
    description: 'Safety, protection, or trust signals.',
    keywords: ['shield', 'trust', 'safe', 'protect', 'security'],
    category: 'objects',
    tone: 'cool',
    clusters: ['support'],
  },
  {
    symbol: '🧘',
    name: 'Mindful Moment',
    description: 'Balance, mindfulness, or reflective content.',
    keywords: ['meditate', 'calm', 'breathe', 'zen', 'focus'],
    category: 'activity',
    tone: 'cool',
    clusters: ['calm'],
  },
  {
    symbol: '🤩',
    name: 'Starry Wow',
    description: 'Delight, wonder, or exciting reveal.',
    keywords: ['wow', 'excited', 'star', 'delight', 'shine'],
    category: 'mood',
    tone: 'playful',
    clusters: ['delight'],
  },
  {
    symbol: '🤝‍🧑',
    name: 'Creative Collaboration',
    description: 'Hands joined in teamwork and co-creation.',
    keywords: ['collab', 'team', 'create', 'together', 'unity'],
    category: 'activity',
    tone: 'neutral',
    clusters: ['collaboration'],
  },
  {
    symbol: '🗺️',
    name: 'World Map',
    description: 'Global perspective, exploration, or travel plans.',
    keywords: ['map', 'global', 'explore', 'journey', 'world'],
    category: 'objects',
    tone: 'cool',
    clusters: ['explore'],
  },
  {
    symbol: '🪄',
    name: 'Magic Wand',
    description: 'Transformation, polished results, or enchanted endings.',
    keywords: ['magic', 'transform', 'sparkle', 'polish', 'wow'],
    category: 'objects',
    tone: 'playful',
    clusters: ['magic'],
  },
  {
    symbol: '🤍',
    name: 'Soft Heart',
    description: 'Gentle appreciation or sincere notes.',
    keywords: ['heart', 'soft', 'care', 'support', 'gentle'],
    category: 'emotions',
    tone: 'neutral',
    clusters: ['support'],
  },
  {
    symbol: '💙',
    name: 'Calm Heart',
    description: 'Trust, calm, and steady encouragement.',
    keywords: ['heart', 'calm', 'trust', 'support', 'steady'],
    category: 'emotions',
    tone: 'cool',
    clusters: ['support'],
  },
  {
    symbol: '🧊',
    name: 'Crystal Cool',
    description: 'Chill vibes, clarity, or refreshing pauses.',
    keywords: ['ice', 'cool', 'clarity', 'refresh', 'calm'],
    category: 'nature',
    tone: 'cool',
    clusters: ['calm'],
  },
  {
    symbol: '🌋',
    name: 'Bold Volcano',
    description: 'Powerful energy, intense focus, or eruptive change.',
    keywords: ['volcano', 'power', 'intense', 'change', 'energy'],
    category: 'nature',
    tone: 'warm',
    clusters: ['momentum'],
  },
  {
    symbol: '🏆',
    name: 'Victory Trophy',
    description: 'Achievements, awards, and standout recognition.',
    keywords: ['trophy', 'win', 'award', 'celebrate', 'success'],
    category: 'activity',
    tone: 'warm',
    clusters: ['celebrations'],
  },
  {
    symbol: '🎁',
    name: 'Gift Wrapped',
    description: 'Surprises, rewards, or giving moments.',
    keywords: ['gift', 'surprise', 'present', 'delight', 'treat'],
    category: 'activity',
    tone: 'playful',
    clusters: ['celebrations'],
  },
  {
    symbol: '🕊️',
    name: 'Peace Dove',
    description: 'Calm resolutions, unity, and harmony.',
    keywords: ['peace', 'dove', 'calm', 'unity', 'resolution'],
    category: 'nature',
    tone: 'cool',
    clusters: ['calm'],
  },
  {
    symbol: '🛰️',
    name: 'Signal Boost',
    description: 'Broadcasting updates or reaching new horizons.',
    keywords: ['satellite', 'signal', 'broadcast', 'tech', 'future'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['innovation'],
  },
  {
    symbol: '🧷',
    name: 'Safekeeping Pin',
    description: 'Hold things together or mark fragile topics.',
    keywords: ['pin', 'safety', 'hold', 'secure', 'support'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['support'],
  },
  {
    symbol: '🪐',
    name: 'Orbiting Planet',
    description: 'Cosmic thinking, future visions, or big-picture plans.',
    keywords: ['planet', 'orbit', 'future', 'vision', 'cosmic'],
    category: 'nature',
    tone: 'cool',
    clusters: ['explore'],
  },
  {
    symbol: '🏖️',
    name: 'Beach Day',
    description: 'Leisure moments, retreats, or well-deserved breaks.',
    keywords: ['beach', 'vacation', 'sun', 'relax', 'fun'],
    category: 'nature',
    tone: 'warm',
    clusters: ['calm'],
  },
  {
    symbol: '📆',
    name: 'Calendar Moment',
    description: 'Reminders, scheduling, or milestone dates.',
    keywords: ['calendar', 'date', 'schedule', 'plan', 'milestone'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['organization'],
  },
  {
    symbol: '🧳',
    name: 'Packed Bag',
    description: 'Trips, transitions, or change in motion.',
    keywords: ['travel', 'bag', 'packing', 'journey', 'adventure'],
    category: 'activity',
    tone: 'neutral',
    clusters: ['explore'],
  },
  {
    symbol: '🗂️',
    name: 'Organized Tabs',
    description: 'Sorting, archiving, or tidy documentation.',
    keywords: ['organize', 'folders', 'files', 'tabs', 'archive'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['organization'],
  },
  {
    symbol: '🔮',
    name: 'Future Vision',
    description: 'Forecasts, predictions, and aspirational ideas.',
    keywords: ['crystal ball', 'future', 'vision', 'mystic', 'plan'],
    category: 'objects',
    tone: 'playful',
    clusters: ['innovation'],
  },
  {
    symbol: '🤖',
    name: 'Friendly Robot',
    description: 'Automation, AI, or tech-forward commentary.',
    keywords: ['robot', 'ai', 'automation', 'tech', 'future'],
    category: 'objects',
    tone: 'neutral',
    clusters: ['innovation'],
  },
];

export const CONTEXT_SUGGESTIONS: Record<'title' | 'content', { label: string; icon: string; keywords: string[] }[]> = {
  title: [
    { label: 'Launch energy', icon: '🚀', keywords: ['launch', 'rocket', 'new'] },
    { label: 'Inspire action', icon: '🎯', keywords: ['goal', 'focus', 'impact'] },
    { label: 'Celebrate wins', icon: '🏆', keywords: ['celebrate', 'victory', 'success'] },
  ],
  content: [
    { label: 'Warm welcome', icon: '😊', keywords: ['welcome', 'thanks', 'care'] },
    { label: 'Story moment', icon: '🧵', keywords: ['story', 'narrative', 'thread'] },
    { label: 'Quick recap', icon: '📌', keywords: ['summary', 'pin', 'remember'] },
  ],
};
