name: CI / Multi-OS Build

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]   # push a version tag to publish a release
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }} / Node ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:   [ubuntu-latest, windows-latest, macos-latest]
        node: [20]   # add more versions if you want to test multiple
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm   # npm|yarn|pnpm

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

      - name: Package
        run: npm run package --if-present
        # e.g. produce ./dist/<platform> files

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: |
            dist/**
            !**/*.map
          retention-days: 14

  release:
    name: Release (attach all builds)
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release and upload assets
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
          artifacts: "artifacts/**/*"
